# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3176330955a070f6619ffc728a43946ce100538c5e3ae41b7a6bd4b6f02d89a6e04b532f642233f5a2e5db830255c745b2f735cb5958b4810169a6e6ffb98ff3

test:
  secret_key_base: 8febc09005bf1cc9fe3bf1ba390db9cb59d75a49148f5c2168f89c794edb31618a3cb9ce1743285ba7aac5c75f2e0e864c237309c52ced5c120495319afe71d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
